#pragma once
#include "commons.h"

#define MESSAGE_MAX_LENGTH 16384
#define USERNAME_MAX_LENGTH 30

#define PACKET_HEADER_SIZE 9
#define PACKET_HEADER_TYPE_INDEX 0
#define PACKET_HEADER_PL_SIZE_INDEX 1
#define PACKET_HEADER_PL_SIZE_SIZE sizeof(uint64_t)

#define PACKET_TYPE_AUTH 0xAA
#define PACKET_TYPE_DEAUTH 0xAB
#define PACKET_TYPE_AUTH_SUCCESS 0xAC

#define PACKET_TYPE_CLIENT_DEAUTH 0xAD
#define PACKET_TYPE_CLIENT_AUTH 0xAE

#define PACKET_TYPE_MESSAGE 0xBA

// CE DOIT ÊTRE LE TYPE AVEC LES 4 BITS HAUT LES PLUS GRANDS DE TOUS LES AUTRES MESSAGES  

#define PACKET_TYPE_ERROR_MSG_TOO_LONG 0xCA
#define PACKET_TYPE_ERROR_INVALID_USERNAME 0xCB
#define PACKET_TYPE_ERROR_INTERNAL_SERVER 0xCC

// PAS D'AUTRES MESSAGES DE LA FORME 0xXY avec 0xX0 > 0xC0 !

typedef struct {
	char header[12];
	char data[MESSAGE_MAX_LENGTH];
	size_t size;
} Packet, *PPacket;

